{
    'name': 'Hospital Management',
    'version': '1.0',
    'sequence':'0',
    'description': 'manage hospital',
    'summary': '',
    'author': 'cupangserit',
    'website': '',
    'license': 'LGPL-3',
    'category': '',
    'depends': [
        'base',
        'mail',
        'sale',
        'contacts',
    ],
    'data': [
        'views/patients_view.xml',
        'views/appointment_view.xml',
        'views/doctor_view.xml',
        'wizards/create_appointment.xml',
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/sequence.xml',
        'data/data.xml',
        'wizards/create_appointment.xml',
        'reports/report.xml',
        'reports/patient_card.xml',
    ],
    'application': True,
}
